### ISSUE TITLE
Rename project protocol paths

### ISSUE THREAD

**Issue by Vilax** [I2PC/scipion#1935]
When a project is renamed, the protocols keep the old path, and when they are relaunched they cannot find the path.

**Comment by pconesa** [comment]
More info: this happens with import volumes, because the import volume protocol has an attribute, outputVol, with an absolute path.

**Comment by pconesa** [comment]
also all volumes (Set) are imported with absolute paths.

**Comment by delarosatrevin** [comment]
Yep, maybe we could remove the absolute path in the output...I have sometimes thought if for volumes we activate the "Copy files" option to True by default. @azazellochg What do you think?

**Comment by pconesa** [comment]
I've fixed it just by making it relative, regardless copy or linking

**Comment by delarosatrevin** [comment]
Wait, wait. I still don't get it. If you are importing a volume outside the
project, how the project renaming affect the abs link?

**Comment by pconesa** [comment]
Because the filename for the volume object stored was absolute.

**Comment by pconesa** [comment]
Imported volumes point files/links at import's extra folder

**Comment by delarosatrevin** [comment]
I still don't get it. I guess that if you import a volume from location: /x/y/z/volume.mrc
The, in the extra folder, a link is created to /x/y/z/volume.mrc, independently of the location/name of the importing project. If you rename the project, I can't see how this affect the abs link.

**Comment by azazellochg** [comment]
@delarosatrevin yes, the link created in extra folder still works after renaming, the problem is here: 
https://github.com/I2PC/scipion/blob/release-2.0.0-fixes/pyworkflow/em/protocol/protocol_import/volumes.py#L152

**Comment by azazellochg** [comment]
In general, I agree that simply renaming the protocol should not affect its consistency.

**Comment by pconesa** [comment]
The problem will happen is we import from somewhere inside the project.... will that break the link?

**Comment by delarosatrevin** [comment]
Importing from the same project...usually means that there is some relevant output that we are not giving users the way to register it (via viewers, etc). If it is from another project, then it comes down as importing from an external folder, we don't have way to control if you rename a folder in the the filesystem after an import.

**Comment by azazellochg** [comment]
I have a big relion project, I'll try to rename it and see what breaks ;)

**Comment by pconesa** [comment]
I know, I was just thinking that is the "imports" from inside are linked relative...renaming will not break those links

**Comment by delarosatrevin** [comment]
Yes, imports are a bit troublesome...I remember we had discuss in the past and in some cases absolute seems better, but relative in other cases.
