### ISSUE TITLE
Unblue/Summovie can't open input files

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#429]
Hi there,

Whilst trying to run unblur or summovie, we are getting an error that says no such file, please enter a valid filename. We can run unblur and summovie interactively on these files. 

Input stack filename                [my_movie.mrc] : Runs/000115_ProtSummovie/tmp/movie_000001/Foilhole_0001.mrc
00043:    
00044:    No Such File - please enter a valid filename
00045:    
00046:   Input stack filename                [my_movie.mrc] : 32
00047:    
00048:    No Such File - please enter a valid filename
00049:    
00050:   Input stack filename                [my_movie.mrc] : ../../extra/Foilhole_0001.mrc
00051:    
00052:    No Such File - please enter a valid filename
00053:    
00054:   Input stack filename                [my_movie.mrc] : shifts_000001.txt
etc etc

**Comment by azazellochg** [comment]
Hi @andreanans ,
this looks strange. Could you provide a full run.stdout file?
Also can you check if the protocol works for you on test data by running this:
`scipion test tests.em.protocols.test_protocols_grigoriefflab_unblur.TestGrigorieffLabUnBlur`

**Comment by andreanans** [comment]
Is there anyway to manually download the test dataset? The connection at work prevents the syncing scripts from connecting to your server. Here is the full stdout:
RUNNING PROTOCOL -----------------
      Scipion: v1.0.0
   currentDir: /home/andrean/ScipionUserData/projects/test2
   workingDir: Runs/000060_ProtUnblur
      runMode: Continue
          MPI: 1
      threads: 1
len(steps) 2 len(prevSteps) 0
 Starting at step: 1
 Running steps 
STARTED: processMovieStep, step 1
  2016-05-12 17:47:50.077675
Processing movie: Foilhole_0001.mrc
export OMP_NUM_THREADS=1; /remote/frames/andrean/Software/scipion/software/e
m/unblur/bin/unblur  << eof
Runs/000060_ProtUnblur/tmp/movie_000001/Foilhole_0001.mrc
32
../../extra/Foilhole_0001.mrc
shifts_000001.txt
1.100000
YES
2.000000
300.000000
YES
fsc_000001.txt
2.000000
200.000000
1500.000000
1
1
0.100000
10
YES
NO
eof

  
                   **  Welcome to UnBlur  **
                        Version - 1.0.0
 
                   Input Mode: Batch
                  Date & Time: 2016-05-12 17:47:50


Copyright 2015 Howard Hughes Medical Institute. All rights reserved.
Use is subject to Janelia Farm Research Campus Software Copyright 1.1
license terms ( http://license.janelia.org/license/jfrc_copyright_1_1.html )

Input stack filename                [my_movie.mrc] : Runs/000060_ProtUnblur/tmp/
movie_000001/Foilhole_0001.mrc
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : 32
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : ../../extra/Foilhole_0001.m
rc
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : shifts_000001.txt
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : 1.100000
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : YES
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : 2.000000
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : 300.000000
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : YES
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : fsc_000001.txt
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : 2.000000
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : 200.000000
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : 1500.000000
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : 1
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : 1
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : 0.100000
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : 10
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : YES
 
 No Such File - please enter a valid filename
 
Input stack filename                [my_movie.mrc] : NO
 
 No Such File - please enter a valid filename
 
forrtl: severe (24): end-of-file during read, unit 5, file /proc/22685/fd/0
Input stack filename                [my_movie.mrc] : ERROR: Movie Foilhole_0001.
mrc failed

erasing.....movieFolder:  Runs/000060_ProtUnblur/tmp/movie_000001
FINISHED: processMovieStep, step 1
  2016-05-12 17:47:50.189688
STARTED: createOutputStep, step 2
  2016-05-12 17:47:50.204873
FINISHED: createOutputStep, step 2
  2016-05-12 17:47:50.269867
Cleaning temporarly files....
------------------- PROTOCOL FINISHED

**Comment by azazellochg** [comment]
@andreanans , I'm not sure if there is an easy way ( @delarosatrevin maybe you know? ), but you could do it this way:

```
mkdir movies; cd movies
wget "http://scipion.cnb.csic.es/downloads/scipion/data/tests/movies/MANIFEST"
for i in `awk '{print $1}' MANIFEST`;do wget -x "http://scipion.cnb.csic.es/downloads/scipion/data/tests/movies/${i}" ;done
mv scipion.cnb.csic.es/downloads/scipion/data/tests/movies/* .
rm -rf scipion.cnb.csic.es
```

Then copy this movies folder to your `$SCIPION_HOME/data/tests/` and relaunch the test.

As for your problem, I suggest you do update to the latest changes in 1.0 branch by doing `git pull && scipion install -j 4` in scipion folder. It looks like the problem in input conversion step to me, since Input stack filename points to the wrong path.

**Comment by delarosatrevin** [comment]
Hi @andreanans , the datasets scripts tries to read the MANIFEST and check if the version of the files online is newer. It does not sync, I think a normal download, I don't know why are block in your work. 

Anyway, I agree with @azazellochg  that looks like a conversion problem. What is the original movies format? Could you provide one or two movies for us to test? It would be great if you could also provide the exact parameters you used for import and for summovie/unblur. You can select all these boxes and export the workflow, which is a simple text file that you can email us or even past it here. For the movies probably your will need some place where we could download them. 

Thanks for your feedback and I'm sorry for the inconveniences.

**Comment by azazellochg** [comment]
@delarosatrevin I found the bug. Protocol indeed crashes if input movie ends with ".mrc"

**Comment by delarosatrevin** [comment]
Hum, I didn't explicit assign this issue to @azazellochg...maybe GitHub did that from the @mention ?
Well, thanks both of you...I will take a look in the fix proposed.

**Comment by azazellochg** [comment]
@delarosatrevin, Github assigns it as soon as I mention it in the PR :)

**Comment by delarosatrevin** [comment]
Ok, I have some other issues apart from the filename extension...I will let you know and commit to the PR branch.

**Comment by delarosatrevin** [comment]
@andreanans , I have fixed the issues with summovie and unblur protocols. Thanks a lot for your feedback, I must say that we added these protocols to v1.0 version, but we started a re-factoring in another branch (scipion-box). That's the reason the were a bit out-of-date, I'm sorry for that. 

I have fixed the issues you reported and I asked @azazellochg to double check.
Thanks again.

**Comment by andreanans** [comment]
Thank you,

Just a quick question. At what point will these fixes be released? I did a
git pull to make sure I'm updated to the latest version but the unblur bug
still exists. Do we have to wait until the next official release? Apologies
for the naive question.

Cheers,

Andrea

**Comment by delarosatrevin** [comment]
Hi Andrea, 
You don't need to apologize. In which branch do you are? (I guess that 'master', if you follow the installation instructions. The next bug-fixing release will be soon, but you can try now if you move to the v1.0 branch. This release should be based on the v1.0.0 release but with some bug-fixes. To move to that branch, you should do:

git checkout -b v1.0 -t origin/v1.0
git pull
./scipion install -j 5

After that, you should have the recent summovie and unblur changes. 
Please let me know if we can help with anything else.

Cheers,
Jose Miguel.

**Comment by andreanans** [comment]
Great, thanks. Working nicely now. Any chance you've had a look into the
frealign stack query I posted a week or so ago?

Andrea

**Comment by delarosatrevin** [comment]
We looked at it and we did not found any problem with our test datasets and we haven't had time to investigate this issue in detail. Could your provide us a few images for which we could reproduce the problem you reported?

**Comment by andreanans** [comment]
Hi Jose,

I just added another comment to my frealign issue and uploaded a couple
images form the TestMixedBPV dataset.

Cheers
Andrea
