### ISSUE TITLE
wrong join sets

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#608]
We have a problem merging two SetOfParticles. It works, but the result is wrong. I have looked in particles.sqlite files that are supposed to be joined and they have the same label_property in Class table. The only thing is they have different order of columns (column_name order differs). As far as I understand for joining sets to proceed the program must check if columns are the same, however it looks like it does not sort sqlite table before joining and just selects order of columns as in 1st file.

Anyway, I have attached two input particle sets and the output [**UPD**]. 
https://mega.nz/#!0toDiaxB!K8ABOnAdl0YsOco3FA389WiN4oVkz5MTOCbsRlWJs8E
https://mega.nz/#!Q0omzShR!NIo8e4lRsMfNl18p_J9t2ZnkSN_moGiXxYzFxzrOmT4
https://mega.nz/#!FwxCVAjR!CFr-HDpYkNzbcuR8oyOulsLE7zFvoFyZ46e03rF9kzE

**Comment by azazellochg** [comment]
was this fixed by #654 ?

**Comment by delarosatrevin** [comment]
Unfortunately, this is not fixed yet. I will check this issue now that I have this thing fresh in my mind. I have also found other problems related to #654 that need to be fixed.

**Comment by rmarabini** [comment]
Hi,

  Cannot replica the issue. " setOfparticles with different column order seems to join properlly.

I have create the test

./scipion test tests.em.protocols.test_protocols_sets.TestSets.testMergeAlternateColumn

that creates 2 setsofparticles

a) set of particles 1

sqlite> select * from classes;
1|self|c00|Particle
2|_index|c01|Integer
3|_filename|c02|String
4|_samplingRate|c03|Float
5|_micId|c04|Integer
6|_classId|c05|Integer
7|_attrb1|c06|Float
8|_attrb2|c07|Float

sqlite> select * from Objects;
1|1|||2017-02-13 18:47:03|1|Tmp/particles.stk|1.0|1|1|11.0|21.0
2|1|||2017-02-13 18:47:03|2|Tmp/particles.stk|1.0|2|2|12.0|22.0

b) set of particles 2
sqlite> select * from classes;
1|self|c00|Particle
2|_index|c01|Integer
3|_filename|c02|String
4|_samplingRate|c03|Float
5|_micId|c04|Integer
6|_classId|c05|Integer
7|_attrb2|c06|Float
8|_attrb1|c07|Float
sqlite> select * from Objects;
1|1|||2017-02-13 18:50:05|1|Tmp/particles.stk|2.0|1|1|23.0|13.0
2|1|||2017-02-13 18:50:05|2|Tmp/particles.stk|2.0|2|2|24.0|14.0



c) join result

sqlite> select * from classes;
1|self|c00|Particle
2|_index|c01|Integer
3|_filename|c02|String
4|_samplingRate|c03|Float
5|_micId|c04|Integer
6|_classId|c05|Integer
7|_attrb2|c06|Float
8|_attrb1|c07|Float
9|_acquisition|c08|Acquisition
10|_acquisition._magnification|c09|Float
11|_acquisition._voltage|c10|Float
12|_acquisition._sphericalAberration|c11|Float
13|_acquisition._amplitudeContrast|c12|Float
14|_acquisition._doseInitial|c13|Float
15|_acquisition._dosePerFrame|c14|Float
sqlite> select * from Objects;
1|1|||2017-02-13 18:50:13|1|Tmp/particles.stk|7.08|1|1|21.0|11.0||10000.0|200.0|2.0|0.1|0.0|
2|1|||2017-02-13 18:50:13|2|Tmp/particles.stk|7.08|2|2|22.0|12.0||10000.0|200.0|2.0|0.1|0.0|
3|1|||2017-02-13 18:50:13|1|Tmp/particles.stk|7.08|1|1|23.0|13.0||10000.0|200.0|2.0|0.1|0.0|
4|1|||2017-02-13 18:50:13|2|Tmp/particles.stk|7.08|2|2|24.0|14.0||10000.0|200.0|2.0|0.1|0.0|


This test should be available as soon as the pullrequest is accepted.

**Comment by azazellochg** [comment]
@rmarabini I have updated the links in the first post. Could you check it?

**Comment by rmarabini** [comment]
I have downloaded @azazellochg sets od imsges and they seems to be OK. The particle IDs are different 8in the ourput file) but there is no way around this since many IDs are in both input setOfimages. 

@azazellochg, Could you describe the problem in detail? The test data set contains  200000 particles and 40 columns so I may be checking the wrong columns/particles

**Comment by azazellochg** [comment]
Ok, so I just did join sets in devel (2017-02-13) b217dd68e6:
1. Import both sets into scipion
2. run join sets
3. analyze results, switch to table mode

In the inputs defocus values are in 6000-25000nm range. When you scroll down the output table, looking at the defocus values in 0-3 nm range, the other half is in correct range. All values are obviously wrong.

**Comment by rmarabini** [comment]
Hi,

  Still I cannot replicate the problem. This time I has been working with the files provided by @azazellochg. First I describe what I did and then a request a few extra details regarding the join problem to @azazellochg

=====DESCRIPTION===========
I loaded the particles_output.sqlite using sqlite3 

      sqlite3 particles_output.sqlite

 Then I checked the number of rows

     select count (*) from objects;

The result is 188778
Then I attached particleSets particles1.sqlite and particles2.sqlite.

   sqlite> attach database 'particles1.sqlite' as p1;
   sqlite> attach database 'particles2.sqlite' as p2;
  
   and compute the number of rows. 
       select count (*) from p1.objects;
       select count (*) from p2.objects;
      getting 156030 and 32748 respectively

After that I checked how many rows in  particles_output.sqlite are identical to
a row in  particles1.sqlite

  select count (*), objects.c01, objects.c02  from objects join p2.objects as kk where objects.c02=kk.c02 and objects.c01=kk.c01 and objects.c23=kk.c23;

I defined identical as those rows which have the same index (c01), filename (c02) and defocusU (c23)
the number is 156030
I also check if there is a one to one correspondence between both databases

    select count (*), objects.c01, objects.c02  from objects join p1.objects as kk where objects.c02=kk.c02 and objects.c01=kk.c01 and objects.c23=kk.c23 group by kk.c02, kk.c01, kk.c23 having count(*)> 1; --result of this query is NULL

Finally I repeated the computation with  particles2.sqlite getting 

    32748 rows and NULL again

My conclusion is that particles_output.sqlite  seems to be OK (at least for c01, c02 and c23 attributes). (I do not claim anything about what is shown when this metadata is displayed or for any other attribute). 

==========REQUEST==============
Petition: Before going ahead can you specify a row (index, filename and defocusU) that is not properly handled after the join?

**Comment by azazellochg** [comment]
@rmarabini I see, the current method basically joins the sets based on column name (cXX)?. The thing is that the _ctfModel._defocusU is c23 in particles1 and c07 in particles2 ! So the label_property should be compared first and not column name.

**Comment by delarosatrevin** [comment]
This issue is not solved yet.
